apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-demo
  template:
    metadata:
      labels:
        app: aks-demo
    spec:
      containers:
      - name: aks-demo
        image: aksdemoacr456.azurecr.io/aks-demo:latest
        ports:
        - containerPort: 3000
